stages:
  - build
  - test
  - deploy

# See https://docs.gitlab.com/ce/ci/docker/using_docker_build.html for overlayfs tip
variables:
  TAG: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
  DOCKER_DRIVER: overlay2

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - set
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${TAG} .
    - docker push ${TAG}

# test.python:
#   image: $TAG
#   stage: test
#   script:
#     - python manage.py test --settings=gamecraft.settings_test

test.nomad:
  image: gitlab.twomeylee.name:7443/twomeylee/nomad-jobs:latest
  stage: test
  script:
    - validate

deploy_production:
  image: gitlab.twomeylee.name:7443/twomeylee/nomad-jobs:latest
  stage: deploy
  environment:
    name: production
    url: http://codinggrace.twomeylee.name/
  script:
    - deploy
  when: manual
  only:
    - master
