stages:
  - build
  - test
  - deploy

# See https://docs.gitlab.com/ce/ci/docker/using_docker_build.html for overlayfs tip
variables:
  TAG: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
  DOCKER_DRIVER: overlay2

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - set
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${TAG} .
    - docker push ${TAG}
